global:
  seed: 42
  train_batch_size: 32
  eval_batch_size: 64
  print_train_loss_every: 1000
  max_epochs: 100
  validate_every: null
  patience: 10
  criterion: "auc"
  gradient_accumulation_steps: 1
  grad_clip: 1.0 #0.3
  weight_decay: 1e-4
  loss_fn: "bce"
  calibrate_threshold: 0
  window_forecast: 10080
  window_pred: 1440
  pos_class_weight: 0

tcn:
  default:
    variant: "VMD"
    hid_dim: 128
    num_layers: 6
    dropout: 0.2
    kernel_size: 4
    lr: 5e-4
    agg: "mean"
    impute: "fill"
    pos_class_weight: 0

  grid_search:
    variant: ["VMD"]
    hid_dim: [64, 128]
    num_layers: [4, 6]
    dropout: [0.2, 0.3]
    kernel_size: [4]
    lr: [1e-4, 5e-4]
    agg: ["mean"]
    impute: ["fill"]
    pos_class_weight: [0, 1]

gru:
  default:
    variant: "VMD"
    hid_dim: 128
    num_layers: 1
    dropout: 0.2
    lr: 5e-4
    agg: "mean"
    impute: "fill"
    pos_class_weight: 0

  grid_search:
    variant: ["VMD"]
    hid_dim: [64, 128]
    num_layers: [1, 2]
    dropout: [0.2, 0.3]
    lr: [1e-4, 5e-4]
    agg: ["mean"]
    impute: ["fill"]
    pos_class_weight: [0, 1]

lstm:
  default:
    variant: "VMD"
    hid_dim: 128
    num_layers: 1
    dropout: 0.2
    lr: 5e-4
    agg: "mean"
    impute: "fill"
    pos_class_weight: 0

  grid_search:
    variant: ["VMD"]
    hid_dim: [64, 128]
    num_layers: [1, 2]
    dropout: [0.2, 0.3]
    lr: [1e-4, 5e-4]
    agg: ["mean"]
    impute: ["fill"]
    pos_class_weight: [0, 1]
    
sand:
  default:
    variant: "VMD"
    hid_dim: 128
    num_layers: 4
    dropout: 0.2 
    num_heads: 4
    M: 12
    r: 24
    lr: 5e-4
    agg: "mean"
    impute: "fill"
    pos_class_weight: 0

  grid_search:
    variant: ["VMD"]
    hid_dim: [64, 128]
    num_layers: [4]
    dropout: [0.2, 0.3]
    num_heads: [2, 4]
    M: [12]
    r: [24]
    lr: [1e-4, 5e-4]
    agg: ["mean"]
    impute: ["fill"]
    pos_class_weight: [0, 1]
    
grud:
  default:
    max_timesteps: 1000
    hid_dim: 64
    dropout: 0.2 
    lr: 5e-4
    pos_class_weight: 0

  grid_search:
    max_timesteps: [1000]
    hid_dim: [64, 128]
    dropout: [0.2, 0.3]
    lr: [1e-4, 5e-4]
    pos_class_weight: [0, 1]
    
interpnet:
  default:
    max_timesteps: 1000
    hid_dim: 64
    hours_look_ahead: 48
    ref_points: 192
    dropout: 0.2
    lr: 5e-4
    pos_class_weight: 0

  grid_search:
    max_timesteps: [1000]
    hid_dim: [64, 128]
    hours_look_ahead: [48, 120]
    ref_points: [192]
    dropout: [0.2, 0.3]
    lr: [1e-4, 5e-4]
    pos_class_weight: [0, 1]
    
strats:
  default:
    max_obs: 1000
    hid_dim: 128
    num_layers: 2
    num_heads: 8
    attention_dropout: 0.2
    dropout: 0.2
    lr: 5e-4
    pos_class_weight: 0
    
  grid_search:
    max_obs: [1000]
    hid_dim: [64, 128]
    num_layers: [2, 4]
    num_heads: [8, 16]
    attention_dropout: [0.2]
    dropout: [0.2, 0.3]
    lr: [1e-4, 5e-4]
    pos_class_weight: [0, 1]

mlp:
  grid_search:
    variant: ["VMD"]
    hid_dims: [[64], [128], [128, 64], [256, 128]]
    dropout: [0.2, 0.3]
    lr: [1e-4, 5e-4]
    agg: ["mean"]
    impute: ["fill"]
    pos_class_weight: [0, 1]

random_forest:
  default:
    n_estimators: 150
    max_depth: 10
    min_samples_split: 5
    variant: VMD
    impute: fill
    feature_combination_method: concatenate
  grid_search:
    variant: [VMD] # Only with concatenate
    impute: [fill]
    feature_combination_method: [concatenate]
    n_estimators: [100, 200,250]
    max_depth: [5, 10]
    min_samples_split: [5, 10,15]
    class_weight:
    - {0: 1, 1: 1}
    - {0: 1, 1: 2}
logistic_regression:
  default:
    C: 0.1
    penalty: l2
    max_iter: 2000
    variant: VMD
    impute: fill
    feature_combination_method: concatenate
  grid_search:
    variant: [VMD]
    impute: [fill]
    feature_combination_method: [aggregate, concatenate]
    C: [0.01, 0.1, 1]
    penalty: [l2]
    max_iter: [2000]

gradient_boosting:
  default:
    variant: VMD
    impute: fill
    feature_combination_method: concatenate
    learning_rate: 0.1
    max_iter: 200
    max_depth: 5
  grid_search:
    variant: [VMD]
    impute: [fill]
    feature_combination_method: [concatenate]
    learning_rate: [0.01, 0.1]
    max_iter: [100, 200]
    max_depth: [5, 10]

xgboost:
  default:
    variant: VMD
    impute: fill
    feature_combination_method: concatenate
    learning_rate: 0.1
    max_depth: 5
    n_estimators: 200
    scale_pos_weight: 2
  grid_search:
    variant: [VMD]
    impute: [fill]
    feature_combination_method: [concatenate]
    learning_rate: [0.01, 0.1]
    max_depth: [3, 5]
    n_estimators: [100, 200]
    scale_pos_weight: [1, 2]

catboost:
  default:
    variant: VMD
    impute: fill
    feature_combination_method: concatenate
    learning_rate: 0.1
    depth: 6
    n_estimators: 300
    allow_writing_files: false
    verbose: false
  grid_search:
    variant: [VMD]
    impute: [fill]
    feature_combination_method: [concatenate]
    learning_rate: [0.03, 0.1]
    depth: [4, 6]
    n_estimators: [200, 300]
    allow_writing_files: [false]
    verbose: [false]