name: flabbench

channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26.4
  - pandas
  - scikit-learn=1.0.2
  - scipy
  - matplotlib
  - lightgbm
  - catboost
  - py-xgboost
  - imbalanced-learn
  - numba
  - shap
  - tqdm
  - jupyterlab
  - ipywidgets
  - notebook
  - python-graphviz
  - seaborn
  - umap-learn

  - pip:
    # not for HPC
    # - torch==2.0.0+cu117
    #  - torchvision==0.15.1+cu117
    # - torchaudio==2.0.1
    - optuna==4.8.0
    - transformers==4.35.2
    - pyarrow