global:
  seed: 42
  train_batch_size: 32
  eval_batch_size: 64
  print_train_loss_every: 1000
  max_epochs: 100
  validate_every: null
  patience: 10
  criterion: loss
  gradient_accumulation_steps: 1
  grad_clip: 1.0
  weight_decay: 1e-4
  loss_fn: bce
  calibrate_threshold: 0
  window_forecast: 10080
  window_pred: 1440
sand:
  mimic_cohort_aplasia_45_days:
    variant: VMD
    hid_dim: 64
    num_layers: 4
    dropout: 0.2
    num_heads: 2
    M: 12
    r: 24
    lr: 0.0005
    agg: mean
    impute: fill
    pos_class_weight: 1
    mean_epochs: 23
  mimic_cohort_NF_30_days:
    variant: VMD
    hid_dim: 64
    num_layers: 4
    dropout: 0.3
    num_heads: 2
    M: 12
    r: 24
    lr: 0.0005
    agg: mean
    impute: fill
    pos_class_weight: 1
    mean_epochs: 13